# Generated by Django 4.1 on 2022-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("admin", models.BooleanField(default=False)),
                ("staff", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
