# Generated by Django 4.1 on 2022-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
