# Generated by Django 4.1 on 2022-11-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menumodel_name'),
        ('stock', '0003_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='menu',
            field=models.ManyToManyField(to='menu.menumodel'),
        ),
    ]
